spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: greet-service
          uri: http://localhost:8081
          predicates:
            - Path=/greet
          filters:
            - AddRequestHeader=gateway-req-header,gtway-hvalue
            - AddResponseHeader=gateway-resp-header,gtway-hvalue

server:
  port: 8080


